services:
  etl:
    build:
      context: .
      dockerfile: ./etl/Dockerfile
    env_file:
      - ./etl/.env
    restart: on-failure
    depends_on:
      - theatre-db
      - elasticsearch

  theatre-db:
    image: postgres:16
    env_file:
      - ./etl/.env
    ports:
      - "5432:5432"
    volumes:
      - theatre_data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  theatre_data:
  elasticsearch_data: